version: '3.8'

services:
  web:
    build: .
    container_name: crowdmonitor-dashboard
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - FLASK_ENV=development
